// Generated from cacus_team_sorted_final.csv
export const caucusMembers = [
  {
    name: "Tim Ackert",
    nameUrl: "https://www.cthousegop.com/Ackert",
    district: "8",
    contactUrl: "https://www.cthousegop.com/Ackert/contact",
  },
  {
    name: "Mark Anderson",
    nameUrl: "https://www.cthousegop.com/Anderson",
    district: "62",
    contactUrl: "https://www.cthousegop.com/Anderson/contact",
  },
  {
    name: "Chris Aniskovich",
    nameUrl: "https://www.cthousegop.com/Aniskovich",
    district: "35",
    contactUrl: "https://www.cthousegop.com/Aniskovich/contact",
  },
  {
    name: "Mitch Bolinsky",
    nameUrl: "https://www.cthousegop.com/Bolinsky",
    district: "106",
    contactUrl: "https://www.cthousegop.com/Bolinsky/contact",
  },
  {
    name: "Seth Bronko",
    nameUrl: "https://www.cthousegop.com/Bronko",
    district: "70",
    contactUrl: "https://www.cthousegop.com/Bronko/contact",
  },
  {
    name: "Jason Buchsbaum",
    nameUrl: "https://www.cthousegop.com/buchsbaum",
    district: "69",
    contactUrl: "https://www.cthousegop.com/buchsbaum/contact/",
  },
  {
    name: "Bill Buckbee",
    nameUrl: "https://www.cthousegop.com/Buckbee",
    district: "67",
    contactUrl: "https://www.cthousegop.com/Buckbee/contact",
  },
  {
    name: "Patrick Callahan",
    nameUrl: "https://www.cthousegop.com/Callahan",
    district: "108",
    contactUrl: "https://www.cthousegop.com/Callahan/contact",
  },
  {
    name: "Vincent Candelora",
    nameUrl: "https://www.cthousegop.com/Candelora",
    district: "86",
    contactUrl: "https://www.cthousegop.com/Candelora/contact",
  },
  {
    name: "Joe Canino",
    nameUrl: "https://www.cthousegop.com/canino/",
    district: "65",
    contactUrl: "https://www.cthousegop.com/canino/contact/",
  },
  {
    name: "Devin Carney",
    nameUrl: "https://www.cthousegop.com/Carney",
    district: "23",
    contactUrl: "https://www.cthousegop.com/Carney/contact",
  },
  {
    name: "Christie Carpino",
    nameUrl: "https://www.cthousegop.com/Carpino",
    district: "32",
    contactUrl: "https://www.cthousegop.com/Carpino/contact",
  },
  {
    name: "Jay Case",
    nameUrl: "https://www.cthousegop.com/Case/",
    district: "63",
    contactUrl: "https://www.cthousegop.com/Case/contact",
  },
  {
    name: "Tina Courpas",
    nameUrl: "https://www.cthousegop.com/courpas/",
    district: "149",
    contactUrl: "https://www.cthousegop.com/courpas/contact/",
  },
  {
    name: "Anne Dauphinais",
    nameUrl: "https://www.cthousegop.com/Dauphinais",
    district: "44",
    contactUrl: "https://www.cthousegop.com/Dauphinais/contact",
  },
  {
    name: "Mark DeCaprio",
    nameUrl: "https://www.cthousegop.com/DeCaprio",
    district: "48",
    contactUrl: "https://www.cthousegop.com/DeCaprio/contact",
  },
  {
    name: "Tom Delnicki",
    nameUrl: "https://www.cthousegop.com/Delnicki",
    district: "14",
    contactUrl: "https://www.cthousegop.com/Delnicki/contact",
  },
  {
    name: "Doug Dubitsky",
    nameUrl: "https://www.cthousegop.com/Dubitsky",
    district: "47",
    contactUrl: "https://www.cthousegop.com/Dubitsky/contact",
  },
  {
    name: "Craig Fishbein",
    nameUrl: "https://www.cthousegop.com/Fishbein",
    district: "90",
    contactUrl: "https://www.cthousegop.com/Fishbein/contact",
  },
  {
    name: "Martin Foncello",
    nameUrl: "https://www.cthousegop.com/Foncello",
    district: "107",
    contactUrl: "https://www.cthousegop.com/Foncello/contact",
  },
  {
    name: "Irene Haines",
    nameUrl: "https://www.cthousegop.com/Haines",
    district: "34",
    contactUrl: "https://www.cthousegop.com/Haines/contact",
  },
  {
    name: "Carol Hall",
    nameUrl: "https://www.cthousegop.com/Hall",
    district: "59",
    contactUrl: "https://www.cthousegop.com/Hall/contact",
  },
  {
    name: "Greg Howard",
    nameUrl: "https://www.cthousegop.com/Howard",
    district: "43",
    contactUrl: "https://www.cthousegop.com/Howard/contact",
  },
  {
    name: "Joe Hoxha",
    nameUrl: "https://www.cthousegop.com/Hoxha",
    district: "78",
    contactUrl: "https://www.cthousegop.com/Hoxha/contact",
  },
  {
    name: "Arnold Jensen",
    nameUrl: "https://www.cthousegop.com/jensen",
    district: "131",
    contactUrl: "https://www.cthousegop.com/jensen/contact/",
  },
  {
    name: "Kathy Kennedy",
    nameUrl: "https://www.cthousegop.com/Kennedy",
    district: "119",
    contactUrl: "https://www.cthousegop.com/Kennedy/contact",
  },
  {
    name: "Nicole Klarides-Ditria",
    nameUrl: "https://www.cthousegop.com/Klarides-Ditria",
    district: "105",
    contactUrl: "https://www.cthousegop.com/Klarides-Ditria/contact",
  },
  {
    name: "Brian Lanoue",
    nameUrl: "https://www.cthousegop.com/Lanoue",
    district: "45",
    contactUrl: "https://www.cthousegop.com/Lanoue/contact",
  },
  {
    name: "Tracy Marra",
    nameUrl: "https://www.cthousegop.com/Marra",
    district: "141",
    contactUrl: "https://www.cthousegop.com/Marra/contact",
  },
  {
    name: "Gale Mastrofrancesco",
    nameUrl: "https://www.cthousegop.com/Mastrofrancesco",
    district: "80",
    contactUrl: "https://www.cthousegop.com/Mastrofrancesco/contact",
  },
  {
    name: "Ben McGorty",
    nameUrl: "https://www.cthousegop.com/McGorty",
    district: "122",
    contactUrl: "https://www.cthousegop.com/McGorty/contact",
  },
  {
    name: "Tammy Nuccio",
    nameUrl: "https://www.cthousegop.com/Nuccio",
    district: "53",
    contactUrl: "https://www.cthousegop.com/Nuccio/contact",
  },
  {
    name: "Tom O'Dea",
    nameUrl: "https://www.cthousegop.com/ODea",
    district: "125",
    contactUrl: "https://www.cthousegop.com/ODea/contact",
  },
  {
    name: "Pavalock-D'Amato",
    nameUrl: "https://www.cthousegop.com/pavalock",
    district: "77",
    contactUrl: "https://www.cthousegop.com/pavalock/contact",
  },
  {
    name: "John Piscopo",
    nameUrl: "https://www.cthousegop.com/Piscopo",
    district: "76",
    contactUrl: "https://www.cthousegop.com/Piscopo/contact",
  },
  {
    name: "Bill Pizzuto",
    nameUrl: "https://www.cthousegop.com/Pizzuto",
    district: "71",
    contactUrl: "https://www.cthousegop.com/Pizzuto/contact",
  },
  {
    name: "Joe Polletta",
    nameUrl: "https://www.cthousegop.com/Polletta",
    district: "68",
    contactUrl: "https://www.cthousegop.com/Polletta/contact",
  },
  {
    name: "Karen Reddington-Hughes",
    nameUrl: "https://www.cthousegop.com/Reddington-Hughes",
    district: "66",
    contactUrl: "https://www.cthousegop.com/Reddington-Hughes/contact",
  },
  {
    name: "Amy Romano",
    nameUrl: "https://www.cthousegop.com/romano",
    district: "113",
    contactUrl: "https://www.cthousegop.com/romano/contact-me/",
  },
  {
    name: "David Rutigliano",
    nameUrl: "https://www.cthousegop.com/Rutigliano",
    district: "123",
    contactUrl: "https://www.cthousegop.com/Rutigliano/contact",
  },
  {
    name: "Tony Scott",
    nameUrl: "https://www.cthousegop.com/Scott",
    district: "112",
    contactUrl: "https://www.cthousegop.com/Scott/contact",
  },
  {
    name: "Chris Stewart",
    nameUrl: "https://www.cthousegop.com/stewart/",
    district: "51",
    contactUrl: "https://www.cthousegop.com/stewart/contact",
  },
  {
    name: "Kurt Vail",
    nameUrl: "https://www.cthousegop.com/Vail",
    district: "52",
    contactUrl: "https://www.cthousegop.com/Vail/contact",
  },
  {
    name: "Donna Veach",
    nameUrl: "https://www.cthousegop.com/Veach",
    district: "30",
    contactUrl: "https://www.cthousegop.com/Veach/contact",
  },
  {
    name: "Steve Weir",
    nameUrl: "https://www.cthousegop.com/Weir",
    district: "55",
    contactUrl: "https://www.cthousegop.com/Weir/contact",
  },
  {
    name: "Dave Yaccarino",
    nameUrl: "https://www.cthousegop.com/Yaccarino",
    district: "87",
    contactUrl: "https://www.cthousegop.com/Yaccarino/contact",
  },
  {
    name: "Tami Zawistowski",
    nameUrl: "https://www.cthousegop.com/Zawistowski",
    district: "61",
    contactUrl: "https://www.cthousegop.com/Zawistowski/contact",
  },
  {
    name: "Joe Zullo",
    nameUrl: "https://www.cthousegop.com/Zullo",
    district: "99",
    contactUrl: "https://www.cthousegop.com/Zullo/contact",
  },
  {
    name: "Lezlye Zupkus",
    nameUrl: "https://www.cthousegop.com/Zupkus",
    district: "89",
    contactUrl: "https://www.cthousegop.com/Zupkus/contact",
  },
]
